insert into "public"."Permiso" ("nombre", "usuarioCreadorId", "usuarioModificadorId")
values
('Reserva de laboratorio: Reservar laboratorio docente para un curso (Automatico del Sistema ) ', $1, $1),
('Reserva de laboratorio: Ver reservas confirmadas para un curso (Automatico del Sistema) ', $1, $1),
('Reserva de laboratorio: Realizar reserva discrecional 4 Confirmar reservas ', $1, $1),
('Reserva de laboratorio: Ver totalidad de reservas confirmadas + Pasadas + Rechazadas ', $1, $1),
('Reserva de laboratorio: Ver reservas confirmadas generales para docentes ', $1, $1),
('Reserva de laboratorio: Reservar laboratorio docente para la catedra (Automatico del Sistema) ', $1, $1),
('Reserva de laboratorio: Ver reservas confirmadas para la catedra', $1, $1),
('Aplicaciones: Aplicaciones: Ver listado', $1, $1),
('Aplicaciones: Agregar + Editar + Eliminar', $1, $1),
('Aplicaciones: Cargar Practica (Automatico del sistema)', $1, $1),
('Laboratorio abierto: Reservar', $1, $1),
('Laboratorio abierto: Ver mis reservas actuales y pasadas', $1, $1),
('Laboratorio abierto: Ver planilla de tutores y horarios', $1, $1),
('Laboratorio abierto: Confirmar Reservas', $1, $1),
('Laboratorio abierto: Suspender alumno', $1, $1),
('Laboratorio abierto: Des-suspender alumno', $1, $1),
('Laboratorio abierto: Tutores -> Agregar + Editar + Eliminar', $1, $1),
('Laboratorio abierto: Agregar + Editar + Eliminar', $1, $1),
('Laboratorio abierto: Ver listado de materias', $1, $1),
('Laboratorio abierto: Administrar Correlativa', $1, $1),
('Cursos: Mostrar todos', $1, $1),
('Cursos: Agregar + Editar + Eliminar', $1, $1),
('Cursos: Ver "Mis Cursos" (Automatico del Sistema)', $1, $1),
('Divisiones: Agregar + Editar + Eliminar', $1, $1),
('Divisiones: Ver Listado de Divisiones creadas', $1, $1),
('Equipos: Agregar + Editar + Eliminar', $1, $1),
('Equipos: Ver listado de equipos', $1, $1),
('Equipos: Buscar equipo', $1, $1),
('Equipos: Reporte por armario', $1, $1),
('Equipos: Reporte por tipo', $1, $1),
('Equipos: Admin: Puede ver la ubicación de los Equipos', $1, $1),
('Equipos: Reporte por laboratorio', $1, $1),
('Equipos: Agregar + Editar + Eliminar Manuales', $1, $1),
('Equipos préstamo: Prestar', $1, $1),
('Equipos préstamo: Ver Prestamos activos y finalizados', $1, $1),
('Equipos préstamo: Ver "Mis prestamos activos y finalizados"', $1, $1),
('Equipos type: Agregar + Editar + Eliminar', $1, $1),
('Biblioteca: Agregar + Editar + Eliminar Libro', $1, $1),
('Biblioteca: Ver listado de libros', $1, $1),
('Biblioteca: Buscar libro', $1, $1),
('Biblioteca: Puede ver detalles del libro', $1, $1),
('Biblioteca: Editoriales: Puede agregar, editar y Eliminar.', $1, $1),
('Biblioteca préstamos: Prestar', $1, $1),
('Biblioteca préstamos: Ver prestamos activos y finalizados', $1, $1),
('Biblioteca préstamos: Ver "Mis prestamos activos y finalizados"', $1, $1),
('Reporte fallas: Buscar Reportes de Fallas', $1, $1),
('Reporte fallas: Reportar Fallas de Pc/s e Instrumental', $1, $1),
('Reporte fallas: Administrar Reportes de Fallas', $1, $1),
('Actividades para el usuario sge: Publicar y Administrar', $1, $1),
('Actividades para el usuario sge: Ver publicaciones', $1, $1),
('Actividades abiertas: Publicar y Administrar', $1, $1),
('Actividades abiertas: Ver publicaciones', $1, $1),
('Administrador: Puede actualizar el acta de consejeros', $1, $1),
('Administrador: Modificar Atributos', $1, $1),
('Administrador: Modificar Atributos de Administración', $1, $1),
('Administrador: Ver Panel Control Administrador', $1, $1),
('Administrador: El usuario pertenece al grupo Tutor', $1, $1),
('Administrador: El usuario pertenece al grupo Docente', $1, $1),
('Administrador: El usuario pertenece al grupo Consejero Departamental', $1, $1),
('Administrador: Puede ver los resultados de los votos de acta (ex- "puede ver la encuesta docente")', $1, $1),
('Administrador: El usuario pertenece al grupo Pañol', $1, $1),
('Administrador: El usuario pertenece al grupo Alumno', $1, $1),
('Administrador: Puede ver notificaciones en el index principal', $1, $1),
('Administrador: Acceso al SVN', $1, $1),
('Administrador: Ver Ficha Usuario', $1, $1),
('Administrador: Agregar Usuarios a Grupos', $1, $1),
('Administrador: Ofertas Laborales: Agregar / Eliminar -- Ahora --> INSCRIPCIONES ESPECIALES', $1, $1),
('Administrador: El usuario pertenece al grupo Administrador Web', $1, $1),
('Reserva de laboratorio: Agregar y Eliminar de pantalla', $1, $1);
